server:
  port: 8089
spring:
  datasource:
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1 #内存
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE  #嵌入
    driver-class-name: org.h2.Driver
    username: sa
    password:

    #定义DDL脚本
    schema: classpath:db/schema.sql
    #定义DML脚本
    data: classpath:db/data.sql
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true